const CSS_SUPPORTS_PROBES = [
  ["display_grid",           "display",                    "grid"],
  ["display_flex",           "display",                    "flex"],
  ["display_contents",       "display",                    "contents"],
  ["display_flow_root",      "display",                    "flow-root"],
  ["container_type",         "container-type",             "inline-size"],
  ["aspect_ratio",           "aspect-ratio",               "1"],
  ["gap",                    "gap",                        "10px"],
  ["backdrop_filter",        "backdrop-filter",            "blur(4px)"],
  ["content_visibility",     "content-visibility",         "auto"],
  ["subgrid",                "grid-template-columns",      "subgrid"],
  ["color_oklch",            "color",                      "oklch(0.5 0.2 120)"],
  ["color_p3",               "color",                      "color(display-p3 1 0 0)"],
  ["color_lab",              "color",                      "lab(50% 0 0)"],
  ["color_hdr",              "color",                      "color(rec2020 1 0 0)"],
  ["animation_timeline",     "animation-timeline",         "scroll()"],
  ["overscroll_behavior",    "overscroll-behavior",        "contain"],
  ["text_decoration_skip",   "text-decoration-skip-ink",   "auto"],
  ["mask",                   "mask",                       "none"],
  ["clip_path",              "clip-path",                  "circle(50%)"],
  ["scroll_snap",            "scroll-snap-type",           "x mandatory"],
  ["conic_gradient",         "background",                 "conic-gradient(red, blue)"],
  ["math_style",             "math-style",                 "compact"],
  ["text_wrap_balance",      "text-wrap",                  "balance"],
  ["scroll_timeline",        "scroll-timeline",            "none"],
  ["view_timeline",          "view-timeline",              "none"],
  ["anchor_name",            "anchor-name",                "--a"],
  ["field_sizing",           "field-sizing",               "content"],
  ["interpolate_size",       "interpolate-size",           "allow-keywords"],
  ["selector_has",           "selector(:has(*))"],
  ["selector_is",            "selector(:is(*))"],
  ["selector_where",         "selector(:where(*))"],
  ["selector_not",           "selector(:not(*))"],
  ["at_layer",               "@layer"],
  ["at_container",           "@container (min-width: 1px) {}"],
  ["nesting",                "selector(& .x)"],
];

const CSS_COMPUTED_PROBES = [
  "-webkit-font-smoothing",
  "-moz-osx-font-smoothing",
  "text-rendering",
  "image-rendering",
  "font-kerning",
  "font-optical-sizing",
  "font-synthesis",
  "font-variant-ligatures",
  "text-size-adjust",
  "-webkit-text-size-adjust",
  "zoom",
  "appearance",
  "-webkit-appearance",
  "user-select",
  "-webkit-user-select",
  "scrollbar-width",
  "scrollbar-gutter",
  "color-scheme",
  "print-color-adjust",
  "touch-action",
  "overscroll-behavior",
  "-webkit-tap-highlight-color",
  "text-underline-offset",
  "text-decoration-thickness",
  "hyphenate-character",
];
