const MEDIA_QUERIES = {
  "prefers-color-scheme:dark":    "(prefers-color-scheme: dark)",
  "prefers-color-scheme:light":   "(prefers-color-scheme: light)",
  "prefers-reduced-motion":       "(prefers-reduced-motion: reduce)",
  "prefers-reduced-transparency": "(prefers-reduced-transparency: reduce)",
  "pointer:fine":                 "(pointer: fine)",
  "pointer:coarse":               "(pointer: coarse)",
  "hover:hover":                  "(hover: hover)",
  "hover:none":                   "(hover: none)",
  "any-pointer:fine":             "(any-pointer: fine)",
  "any-pointer:coarse":           "(any-pointer: coarse)",
  "any-hover:hover":              "(any-hover: hover)",
  "display-mode:browser":         "(display-mode: browser)",
  "display-mode:standalone":      "(display-mode: standalone)",
  "color-gamut:srgb":             "(color-gamut: srgb)",
  "color-gamut:p3":               "(color-gamut: p3)",
  "color-gamut:rec2020":          "(color-gamut: rec2020)",
  "forced-colors":                "(forced-colors: active)",
  "inverted-colors":              "(inverted-colors: inverted)",
  "prefers-contrast:more":        "(prefers-contrast: more)",
  "prefers-contrast:less":        "(prefers-contrast: less)",
  "dynamic-range:high":           "(dynamic-range: high)",
  "scripting:enabled":            "(scripting: enabled)",
  "scripting:none":               "(scripting: none)",
  "update:fast":                  "(update: fast)",
  "update:slow":                  "(update: slow)",
};
